### ISSUE TITLE
Copy trading ratio

### ISSUE THREAD

**Issue by Pusherman2** [solid0x/copybybit#2]
Hi there,

Interesting project, will be following!

is it perhaps possible to also auto copy trades and auto close once closed by master trader? And how is the ratio determined compared to master traders’ position size and our position size?

kind regards

**Comment by solid0x** [comment]
Hi!

I'm not planning to add auto copy / close of master traders' positions because it is not profitable.

I had data of traders' positions for many months and analysis showed that basically 99% of traders lose their money even they may have impressive gains for a short period of time.

This tool is great for market analysis, watch what positions other traders are opening in the moment and make your own decisions.

Thank you for your interest 🙂
